## To use numpy 
# First we have to make folder of venv and the one ipynb file to execute the file
- we can make .venv as well venv if we don't use the dot before that file than it means that is global

``` command
python -m venv venv
source venv/bin/activate

pip install numpy

In [1]:
import numpy as np


In [2]:
arr_1d = np.array([1,2,3,4,5])
print('1D array: ', arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print('2D array', arr_2d)

1D array:  [1 2 3 4 5]
2D array [[1 2 3]
 [4 5 6]]


In [3]:
py_list = [1,2,3]
print('pyton list multiplication', py_list * 2)

np_array = np.array([1,2,3])
print('Python array multiplication', np_array * 2)

pyton list multiplication [1, 2, 3, 1, 2, 3]
Python array multiplication [2 4 6]


In [ ]:
import time 
start = time.time()
py_list = [i*2 for i in range(1000000000000000000000000000000000000000000)]
print('\n List operation time : ', time.time() - start)

start = time.time()
np_array = np.arange(1000000000000000000000000000000000000000000) * 2
print('\n Numpy operation time : ', time.time() - start)


## Matrices (array from scratch)


In [ ]:
zeros = np.zeros((4,5))
print('zeros array \n', zeros )

ones = np.ones((3,4))
print('ones array \n', ones )

full = np.full((2,3), 8)
print('full array \n', full )



zeros array 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
ones array 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array 
 [[8 8 8]
 [8 8 8]]


# Array properties


In [ ]:
arr = np.array([[1,2,3], [4,5,6]])

print("Shape ", arr.shape)
print("Dimension ", arr.ndim)
print("Size ", arr.size)
print("DType", arr.dtype)




Shape  (2, 3)
Dimension  2
Size  6
DType int64


# Reshaped Array

In [ ]:
arr = np.arange(12)
print('Original array ', arr)

reshaped = arr.reshape((3, 4))
print("\n Reshaped array ", reshaped)

flattened = reshaped.flatten()
print('\n Flattened array ', flattened)

# ravel (return view, instead of the copy)
raveled = reshaped.ravel()
print('\n raveled array ', raveled)

# Transpose
transpose = reshaped.T
print("\n Transpose array ", transpose)




Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transpose array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
