# 2D array

In [22]:
import numpy as np

In [44]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print('specific elem ', arr_2d[1, 2])
print('Entire row ', arr_2d[1])
print('Entire column ', arr_2d[:, 1])

specific elem  6
Entire row  [4 5 6]
Entire column  [2 5 8]


## Sorting

In [45]:
unsorted = np.array([3,5,3,7,2,8,9,1,4,6])
print("Sorted Array ", np.sort(unsorted))

arr_2d_unsorted = np.array([[5, 3],
                            [2, 7],
                            [9, 8]])
print("Sorted 2D Array ", np.sort(arr_2d_unsorted, axis=0))
print("Sorted 2D Array ", np.sort(arr_2d_unsorted, axis=1))



Sorted Array  [1 2 3 3 4 5 6 7 8 9]
Sorted 2D Array  [[2 3]
 [5 7]
 [9 8]]
Sorted 2D Array  [[3 5]
 [2 7]
 [8 9]]


## Filter

In [25]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2 == 0]
print(even_number)

[ 2  4  6  8 10]


## Filter with mask

In [26]:
mask = numbers > 5
print('Numbers greater than 5 ', numbers[mask])

Numbers greater than 5  [ 6  7  8  9 10]


## Fancy indexing vs np.where


In [27]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print("NP where", numbers[where_result])

[1 3 5]
NP where [ 6  7  8  9 10]


In [28]:
condition_array = np.where(numbers > 5, "true", "false")
print(condition_array)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


## Adding and removing data in array


In [32]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = arr1 + arr2
print(combined)
# combined = np.concatenate((arr1, arr2))
combined = np.concat((arr1, arr2))

print(combined)


[5 7 9]
[1 2 3 4 5 6]


## Array compatibility

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("Compatibility shapes ", a.shape == b.shape)

Compatibility shapes  False


## Adding column and row

In [42]:
original = np.array([[1,2], [3,4]])
new_row = np.array([5,6])

with_new_row = np.vstack((original, new_row))
print("With new Row", with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print("With new col", with_new_col)

With new Row [[1 2]
 [3 4]
 [5 6]]
With new col [[1 2 7]
 [3 4 8]]


## Delete

In [43]:
arr = np.array([1,2,3,4,5,6,7,8,9])

deleted = np.delete(arr, 2)
print(deleted)

[1 2 4 5 6 7 8 9]
